apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-05-24T17:36:11Z"
  generation: 2
  labels:
    app: violin-deploy
  name: violin-deploy
  namespace: default
  resourceVersion: "5716"
  uid: 2832ba93-591c-45af-8f2c-2b9a51ea980b
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: violin-deploy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: violin-deploy
    spec:
      containers:
      - image: marait123/violin
        imagePullPolicy: Always
        name: violin
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-05-24T17:36:11Z"
    lastUpdateTime: "2022-05-24T17:36:16Z"
    message: ReplicaSet "violin-deploy-77ff94459b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-24T17:39:59Z"
    lastUpdateTime: "2022-05-24T17:39:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
